<?php
$z[0]=Array("global","",336,363);
$z[0][4]=array();
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("channel","<li><a href='[field:typelink/]'>[field:typename/]</a> </li>",404,503);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[2]=Array("global","",600,630);
$z[2][4]=array();
$z[2][4]['name']="cfg_companyname";
$z[3]=Array("global","",669,695);
$z[3][4]=array();
$z[3][4]['name']="cfg_address";
$z[4]=Array("global","",707,729);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",741,763);
$z[5][4]=array();
$z[5][4]['name']="cfg_fax";

?>