<?php
$z[0]=Array("type","[field:typename /]",59,112);
$z[0][4]=array();
$z[0][4]['typeid']="16";
$z[1]=Array("channelartlist","\r\n                    <li><a target=\"_blank\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n                     ",210,407);
$z[1][4]=array();
$z[1][4]['typeid']="16";
$z[2]=Array("type","[field:typename /]",529,582);
$z[2][4]=array();
$z[2][4]['typeid']="13";
$z[3]=Array("global","",668,696);
$z[3][4]=array();
$z[3][4]['name']="cfg_address_t";
$z[4]=Array("global","",724,749);
$z[4][4]=array();
$z[4][4]['name']="cfg_mobile";
$z[5]=Array("global","",789,811);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",839,861);
$z[6][4]=array();
$z[6][4]['name']="cfg_fax";
$z[7]=Array("global","",900,932);
$z[7][4]=array();
$z[7][4]['name']="cfg_ContactPerson";
$z[8]=Array("global","",960,984);
$z[8][4]=array();
$z[8][4]['name']="cfg_email";
$z[9]=Array("global","",1012,1038);
$z[9][4]=array();
$z[9][4]['name']="cfg_youbian";

?>